openapi: 3.0.0
info:
  version: 1.0.0
  title: HHforURFU vacancies
  description: |
    %README.md%

tags:
  - name: get
    x-displayName: Получение
  - name: add
    x-displayName: Добавление
  - name: remove
    x-displayName: Удаление
  - name: update
    x-displayName: Обновление

paths:
  "/api/responses/add":
    post:
      tags:
        - add
      summary: Добавление нового юзера в БД
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Respons'
      responses:
        "204":
          description: Данные добавлены в БД
        "400":
          description: Ошибка валидации входных данных
        "401":
          description: Ошибка авторизации
        "500":
          description: Внутренняя ошибка сервиса
    
  "/api/responses/get":
    get:
      tags:
        - get
      summary: Получение всех ответов из БД
      responses:
        "200":
          description: Данные вакансий
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Results'
        "400":
          description: Ошибка валидации входных данных
        "401":
          description: Ошибка авторизации
        "500":
          description: Внутренняя ошибка сервиса

  "/api/responses/{vacancy_id}-and-{chat_id}/get":
    get:
      tags:
        - get
      summary: Получение данных вакансии по vacancy_id
      parameters:
        - name: vacancy_id
          in: path
          description: Идентификатор вакансии
          required: true
          schema:
            type: integer
            format: int64
        - name: chat_id
          in: path
          description: Идентификатор чата
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Данные пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Info'
        "400":
          description: Ошибка валидации входных данных
        "401":
          description: Ошибка авторизации
        "500":
          description: Внутренняя ошибка сервиса

  "/api/responses/{vacancy_id}-and-{chat_id}/update":
    put:
      tags:
        - update
      summary: Обновление информации о вакансии в БД
      parameters:
        - name: vacancy_id
          in: path
          description: Идентификатор вакансии
          required: true
          schema:
            type: integer
            format: int64
        - name: chat_id
          in: path
          description: Идентификатор чата
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateRespons'
      responses:
        "204":
          description: Данные добавлены в БД
        "400":
          description: Ошибка валидации входных данных
        "401":
          description: Ошибка авторизации
        "500":
          description: Внутренняя ошибка сервиса

  "/api/responses/{vacancy_id}-and-{chat_id}/remove":
    delete:
      tags:
        - remove
      summary: Удаление пользователя из БД
      parameters:
        - name: vacancy_id
          in: path
          description: Идентификатор вакансии
          required: true
          schema:
            type: integer
            format: int64
        - name: chat_id
          in: path
          description: Идентификатор чата
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "204":
          description: Данные удалены из БД
        "400":
          description: Ошибка валидации входных данных
        "401":
          description: Ошибка авторизации
        "500":
          description: Внутренняя ошибка сервиса

components:
  schemas:
    UpdateRespons:
      type: object
      description: Данные вакансии
      required:
        - vacancy_id
        - chat_id
        - status
      properties:
        vacancy_id:
          type: integer
          format: int64
          description: Уникальный номер вакансии
          x-oapi-codegen-extra-tags:
            db: vacancy_id
        chat_id:
          type: integer
          format: int64
          description: Уникальный номер чата
          x-oapi-codegen-extra-tags:
            db: chat_id
        status:
          type: string
          description: Статус ответа
          x-oapi-codegen-extra-tags:
            db: status

    Respons:
      type: object
      description: Данные пользователя
      required:
        - vacancy_id
        - chat_id
        - status
      properties:
        vacancy_id:
          type: integer
          format: int64
          description: Уникальный номер вакансии
        chat_id:
          type: integer
          format: int64
          description: Уникальный номер чата
        status:
          type: string
          description: Статус вакансии

    Results:
      type: object
      description: Данные ответов
      required:
        - responses
      properties:
        responses:
          type: array
          items:
            description: Данные ответов
            $ref: '#/components/schemas/Info'
          
    Info:
      type: object
      description: Данные
      required:
        - vacancy_id
        - chat_id
        - status
      properties:  
        vacancy_id:
          type: integer
          format: int64
          description: Уникальный номер вакансии
          x-oapi-codegen-extra-tags:
            db: vacancy_id
        chat_id:
          type: integer
          format: int64
          description: Название компании
          x-oapi-codegen-extra-tags:
            db: chat_id
        status:
          type: string
          description: Статус вакансии
          x-oapi-codegen-extra-tags:
            db: status

    Result:
      type: object
      description: Данные пользователя
      required:
        - chat_id
        - nickname
        - company
      properties:
        chat_id:
          type: integer
          format: int64
          description: Уникальный id чата с пользователем
        nickname:
          type: string
          description: nickname пользователя
        company:
          type: string
          description: Название компании