version: 3

includes:
  seekers:
    taskfile: seekers/Taskfile.seekers.yaml
  employers:
    taskfile: employers/Taskfile.employers.yaml
  vacancies:
    taskfile: vacancies/Taskfile.vacancies.yaml
  filters:
    taskfile: filters/Taskfile.filters.yaml
  responses:
    taskfile: responses/Taskfile.responses.yaml

tasks:
  default:
    desc: Список задач
    cmds:
      - task --list
 