version: 3

includes:
  seekers:
    taskfile: seekers/Taskfile.seekers.yaml
  employers:
    taskfile: employers/Taskfile.employers.yaml

tasks:
  default:
    desc: Список задач
    cmds:
      - task --list
 