openapi: 3.0.0
info:
  version: 1.0.0
  title: HHforURFU seekers
  description: |
    %README.md%

tags:
  - name: get
    x-displayName: Получение
  - name: add
    x-displayName: Добавление
  - name: remove
    x-displayName: Удаление
  - name: update
    x-displayName: Обновление

paths:
  "/api/seekers/add":
    post:
      tags:
        - add
      summary: Добавление нового юзера в БД
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        "204":
          description: Данные добавлены в БД
        "400":
          description: Ошибка валидации входных данных
        "401":
          description: Ошибка авторизации
        "500":
          description: Внутренняя ошибка сервиса

  "/api/seekers/{chat_id}/remove":
    delete:
      tags:
        - remove
      summary: Удаление пользователя из БД
      parameters:
        - name: chat_id
          in: path
          description: Идентификатор пользователя
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "204":
          description: Данные удалены из БД
        "400":
          description: Ошибка валидации входных данных
        "401":
          description: Ошибка авторизации
        "500":
          description: Внутренняя ошибка сервиса
    
  "/api/seekers/get":
    get:
      tags:
        - get
      summary: Получение всех пользователей из БД
      responses:
        "200":
          description: Данные пользователей
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Results'
        "400":
          description: Ошибка валидации входных данных
        "401":
          description: Ошибка авторизации
        "500":
          description: Внутренняя ошибка сервиса

  "/api/seekers/{chat_id}/get":
    get:
      tags:
        - get
      summary: Получение данных пользователя по chat_id
      parameters:
        - name: chat_id
          in: path
          description: Идентификатор пользователя
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Данные пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
        "400":
          description: Ошибка валидации входных данных
        "401":
          description: Ошибка авторизации
        "500":
          description: Внутренняя ошибка сервиса

  "/api/seekers/{chat_id}/update":
    put:
      tags:
        - update
      summary: Обновление информации об юзере в БД
      parameters:
        - name: chat_id
          in: path
          description: Идентификатор пользователя
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUser'
      responses:
        "204":
          description: Данные добавлены в БД
        "400":
          description: Ошибка валидации входных данных
        "401":
          description: Ошибка авторизации
        "500":
          description: Внутренняя ошибка сервиса

components:
  schemas:
    UpdateUser:
      type: object
      description: Данные пользователя
      required:
        - nickname
        - f_name
        - s_name
      properties:
        chat_id:
          type: integer
          format: int64
          description: Chat_id пользователя
          x-oapi-codegen-extra-tags:
            db: chat_id
        nickname:
          type: string
          description: nickname пользователя
          x-oapi-codegen-extra-tags:
            db: nickname
        f_name:
          type: string
          description: Имя пользователя
          x-oapi-codegen-extra-tags:
            db: f_name
        s_name:
          type: string
          description: Фамилия пользователя
          x-oapi-codegen-extra-tags:
            db: s_name

    User:
      type: object
      description: Данные пользователя
      required:
        - chat_id
        - nickname
        - f_name
        - s_name
        - resume
      properties:
        chat_id:
          type: integer
          format: int64
          description: Chat_id пользователя
        nickname:
          type: string
          description: nickname пользователя
        f_name:
          type: string
          description: Имя пользователя
        s_name:
          type: string
          description: Фамилия пользователя
        resume:
          type: string
          format: uri
          description: Ссылка на резюме
      
    Results:
      type: object
      description: Данные пользователей
      required:
        - seekers
      properties:
        seekers:
          type: array
          items:
            description: Данные пользователей
            $ref: '#/components/schemas/Info'
          
    Info:
      type: object
      description: Данные
      required:
        - chat_id
        - nickname
        - fname
        - sname
        - resume
      properties:  
        chat_id:
          type: integer
          format: int64
          description: Уникальный id чата с пользователем
          x-oapi-codegen-extra-tags:
            db: chat_id
        nickname:
          type: string
          description: nickname пользователя
          x-oapi-codegen-extra-tags:
            db: nickname
        fname:
          type: string
          description: Имя пользователя
          x-oapi-codegen-extra-tags:
            db: f_name
        sname:
          type: string
          description: Фамилия пользователя
          x-oapi-codegen-extra-tags:
            db: s_name
        resume:
          type: string
          format: uri
          description: Ссылка на резюме
          x-oapi-codegen-extra-tags:
            db: resume

    Result:
      type: object
      description: Данные пользователя
      required:
        - chat_id
        - nickname
        - f_name
        - s_name
        - resume
      properties:
        chat_id:
          type: integer
          format: int64
          description: Уникальный id чата с пользователем
        nickname:
          type: string
          description: nickname пользователя
        f_name:
          type: string
          description: Имя пользователя
        s_name:
          type: string
          description: Фамилия пользователя
        resume:
          type: string
          format: uri
          description: Ссылка на резюме